# Generated by Django 4.2.4 on 2023-08-11 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_bookmodel_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='title',
            field=models.CharField(default='Kitob nomi', max_length=255),
        ),
    ]
